### PR TITLE
Add readme

### PR DESCRIPTION
**Pull request by sorashi**
I think all GitHub repositories should contain a readme to give the reader a quick overview of the project without leaving GitHub. In this PR I created a readme from the [website branch](https://github.com/syndicodefront/infekt/tree/gh-pages) content and I also moved the contents of FAQ.md into the readme. The latter is in a separate commit if you'd happen to want to revert that and keep just the readme.

### CODE REVIEW

**Comment by sorashi** [comment]
You can see the readme in [my fork](https://github.com/sorashi/infekt).

**Comment by sorashi** [comment]
@flakes 
I'm not sure whether I fully understand what you mean.

If you mean that the readme is just a duplicate of the website content and that's inappropriate, then we could re-create the readme to contain just a short description of the project and then refer to the website for the rest. Is that okay?

If you mean there should be a mechanism to make it easier to mirror the content from the website (which is just the [gh-pages](https://github.com/syndicodefront/infekt/tree/gh-pages) branch) to the readme, then that's possible, but would be much easier if the website was transferred to [Jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/).

**Comment by rescene** [comment]
Keep the intro explaining the program and link to the website. Point to Download/Changelog/FAQ webpages instead of duplicating its content.

Complete the readme with info that is useful for (new) developers, how to make a proper bug report ect.

- https://help.github.com/articles/about-readmes/
- https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md

**Comment by sorashi** [comment]
I made the changes
- left the intro
- added links for Downloads, FAQ, Changelog
- left the screenshots

[Readme](https://github.com/syndicodefront/infekt/blob/19d72303cc8f347137388ee954fbb6bec87e1249/README.md) screenshot:

**Comment by flakes** [comment]
Nice work, thanks!

**Pull request merged**
